### PR TITLE
fix jest-editor-support tests breakage

### PR DESCRIPTION
**Pull request by connectdotz**
fix test breakage issue when linking with the newly update `jest-editor-support` see /jest-community/jest-editor-support#14, particular [here](https://github.com/jest-community/jest-editor-support/pull/14#issuecomment-515773884)

Note: this PR will failed ci until we pick up the next `jest-editor-support`

### CODE REVIEW

**Comment by connectdotz** [comment]
the ci error is due to testing with the old `jest-editor-support`, I will mark this PR has a dependency on the next release of  `jest-editor-support`.

**Comment by stephtr** [comment]
Thank you!
If there are no errors after releasing a new version of `jest-editor-support`, I'm happy with merging it.

**Comment by seanpoulter** [comment]
> Thank you!
> If there are no errors after releasing a new version of `jest-editor-support`, I'm happy with merging it.

Me too. 👏

**Comment by connectdotz** [comment]
ok,  the new "jest-editor-support" 27.0.0 is out, I updated the package.json and adjusted the jest config because when installing from npm, some modules under "jest-editor-support/node_modules" got hoisted to the top, so we still have to explicitly unmock those in `unmockedModulePathPatterns`.

we should be ready to merge now.

**Pull request merged**
