### PR TITLE
Add webpack for extension bundling

### PR DESCRIPTION
**Pull request by stephtr**
This PR adds webpack as an extension bundler. This reduces the extension size from > 4000 files and nearly 40 MB (v2.9.2) down to 9 files and less than 4 MB (v3.0.0 branch).

## Notes
- `jest-config` (pulled in due to `jest-editor-support`) is incompatible with Webpack and adds many dependencies, but that part of `jest-editor-support` isn't used by us, which is why I left it unresolved within webpack.
- One usually uses `fork-ts-checker-webpack-plugin` for improving compilation time, but for some reason compile times only went up when using that plugin, independent of its configuration.
- For speeding up development compilation time, I set up webpack (only in dev mode) to also ignore the by far largest packages: `typescript`, `@babel` and `babylon`; those packages get included from `node_modules` just like before.
- For the VS Code watch task I added a problem matcher, which doesn't match any problems. The reason is that this is the only way to wait with launching the debugging VS code window until webpack has finished compilation.

### CODE REVIEW

**Comment by connectdotz** [comment]
> This reduces the extension size from > 4000 files and nearly 40 MB (v2.9.2) down to 9 files and less than 4 MB (v3.0.0 branch).

OMG, that was so cool...

However, when I run vscode with the .vsix package build from this PR (`vsce package --yarn`) it gave me the following error about `jest-config`:

```
Here is the error stack:  Error: Cannot find module 'jest-config'
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
	at Function.Module._load (internal/modules/cjs/loader.js:528:25)
	at Function.define._installInterceptor.i._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:486:42)
	at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:750:857)
	at Function.t.getExtensionPathIndex.then.i._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:676:176)
	at Module.require (internal/modules/cjs/loader.js:658:17)
	at n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:874)
	at Object.module.exports.Object.defineProperty.value (/Users/vsun/.vscode/extensions/orta.vscode-jest-3.0.0/out/extension.js:129:74081)
	at r (/Users/vsun/.vscode/extensions/orta.vscode-jest-3.0.0/out/extension.js:1:279)
	at Object.<anonymous> (/Users/vsun/.vscode/extensions/orta.vscode-jest-3.0.0/out/extension.js:129:71433)
	at r (/Users/vsun/.vscode/extensions/orta.vscode-jest-3.0.0/out/extension.js:1:279)
	at Object.module.exports.Object.defineProperty.value (/Users/vsun/.vscode/extensions/orta.vscode-jest-3.0.0/out/extension.js:32:3481)
	at r (/Users/vsun/.vscode/extensions/orta.vscode-jest-3.0.0/out/extension.js:1:279)
	at Object.module.exports.Object.defineProperty.value (/Users/vsun/.vscode/extensions/orta.vscode-jest-3.0.0/out/extension.js:129:61947)
	at r (/Users/vsun/.vscode/extensions/orta.vscode-jest-3.0.0/out/extension.js:1:279)
	at Object.module.exports.n (/Users/vsun/.vscode/extensions/orta.vscode-jest-3.0.0/out/extension.js:129:12865)
	at r (/Users/vsun/.vscode/extensions/orta.vscode-jest-3.0.0/out/extension.js:1:279)
	at module.exports.Object.defineProperty.value (/Users/vsun/.vscode/extensions/orta.vscode-jest-3.0.0/out/extension.js:1:1078)
	at Object.<anonymous> (/Users/vsun/.vscode/extensions/orta.vscode-jest-3.0.0/out/extension.js:1:1089)
	at Object.<anonymous> (/Users/vsun/.vscode/extensions/orta.vscode-jest-3.0.0/out/extension.js:429:3)
	at Module.t._initNodeRequire.r._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:16:90)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
	at Module.load (internal/modules/cjs/loader.js:620:32)
	at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
	at Function.Module._load (internal/modules/cjs/loader.js:551:3)
	at Function.define._installInterceptor.i._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:486:42)
	at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:750:857)
	at Function.t.getExtensionPathIndex.then.i._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:676:176)
	at Module.require (internal/modules/cjs/loader.js:658:17)
	at require (internal/modules/cjs/helpers.js:20:18)
	at Function.i [as __$__nodeRequire] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:31:542)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:737:450
	at I._doActivateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:737:558)
	at I._activateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:736:404)
	at I.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:733:330)
	at Generator.next (<anonymous>)
	at n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:13:388)
	at new Promise (<anonymous>)
	at n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:13:165)
	at Object.actualActivateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:733:32)
	at p._activateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:474:561)
	at define._activateExtensions.r.length.Promise.all.o.map.e (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:474:245)
	at Array.map (<anonymous>)
	at p._activateExtensions (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:474:233)
	at p.activateById (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:472:355)
	at I._activateById (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:735:132)
	at I.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:740:175)
	at Generator.next (<anonymous>)
	at s (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:13:221)
```

how do we find out which module is asking for `jest-config`?

**Comment by connectdotz** [comment]
will webpack try to load Settings merely because it is in the `jest-editor-support` [index.js](https://github.com/jest-community/jest-editor-support/blob/e087d082431c7f69a661ce1d6eb348690d3abe34/src/index.js#L42)?

**Comment by stephtr** [comment]
> how do we find out which module is asking for jest-config?

Using `yarn why jest-config`, it is just `Settings.js` in `jest-editor-support`, which isn't used by our code at all. For me that was never an issue, however I didn't test it by using the `.vsix` file. I'll take a look at it.

**Comment by stephtr** [comment]
Could you give it another try? It should be fixed.

**Comment by connectdotz** [comment]
much better, I can run with this package now, sweet! great job @stephtr 👍

**Pull request merged**
