### PR TITLE
Adjust test result indicator for colorblind people

### PR DESCRIPTION
**Pull request by jmarceli**
According to https://github.com/jest-community/vscode-jest/issues/500 it might be beneficial to change the failing test icon to easily distinguish it from the success status without any color information.

### CODE REVIEW

**Comment by jmarceli** [comment]
Good idea. Please check if this is what you are looking for.

**Comment by connectdotz** [comment]
the checkmark is a bit small, comparing to the green dot, maybe I am just not used to it yet... lets both try it for a few days to decide...

**Comment by connectdotz** [comment]
it's been a few days, anybody has any objection to merging this PR?

**Comment by bryanjclark** [comment]
Thanks so much for doing this!

**Pull request merged**
