### PR TITLE
use kebab-case

### PR DESCRIPTION
**Pull request by vhdirk**
This PR fixes  https://github.com/jest-community/vscode-jest/issues/923.

Depends on https://github.com/jest-community/jest-editor-support/pull/91

### CODE REVIEW

**Review by connectdotz — COMMENTED** [review]
hi @vhdirk Thanks for submitting this PR 👍 

In addition to the files you updated, there are a few other places that require similar treatment, such as: 
- package.json
- DebugConfigurationProvider and its tests
- process-listeners and its tests: (there is regex looking for watch flags, not sure if it will be impacted, please check when you are at it, thx)

to be consistent. we should probably also update these test cases
- setup-jest-debug.test.ts
- wizard-helper.test.ts

**Comment by connectdotz** [comment]
@vhdirk looks good. 

There are some issues in the jest-community/jest-editor-support#91, let's finish that before merging this, so we can test these changes as a whole. While the changes are quite mechanical, it is significant, we should do more testing...

**Comment by vhdirk** [comment]
@connectdotz Thanks for reviewing. For what it's worth, I've been using this as my daily driver for at least a week now. No issues to be seen :)

**Comment by connectdotz** [comment]
@vhdirk I tested a bit with the new kebab arguments, and bumped into a problem with react-scripts. It seems react-scripts only recognized `"--watchAll=false"` but not `"--watch-all=false"`. I opened an issue facebook/create-react-app#12801 and hopefully, it will be addressed for future versions.

This means we might have to put the CI flag (in `jest-editor-support`) back (but I vaguely remember there were some other conflicts??), or switch between watchAll and watch-all selectively, which definitely sucks and not sure if we can reliably detect react/react-native... thoughts?

**Comment by connectdotz** [comment]
I think an alternative solution is to just pass a flag to jest-editor-support and have it converts all jest arguments accordingly. That way, we don't need to hard-code or change anything on the vscode-jest side (maybe?), what do you think?

**Comment by vhdirk** [comment]
I could also make a PR for https://github.com/facebook/create-react-app/issues/12801, but I suppose it would still mean that every single app ever made with it will also be broken?
That's quite a bummer.

I think adding a flag is pretty much the only way forward, though I don't quite understand how that would mean that we don't have to change anything in vscode-jest. I specifically ran into issues there.

**Comment by vhdirk** [comment]
How do you feel about adding https://www.npmjs.com/package/change-case as a dependency? It would make the code quite a bit cleaner.

**Comment by connectdotz** [comment]
I think it might be a bit overkill, given we only need to consider camel => dash/kebab.

**Comment by vhdirk** [comment]
The same author does offer the library in smaller parts:
 - https://www.npmjs.com/package/param-case
 - https://www.npmjs.com/package/camel-case

If we have to support both options, I'm not very keen on littering the code with stuff like `kebabCase ? '--watch-all' : '--watchAll'`

**Comment by connectdotz** [comment]
It seems this is pretty much a single line function, I did a quick a test and it seems to work:
```ts
it('convert to kebab case', () => {
  const s = 'testNamePath'.replace(/(\B)([A-Z])/gm, '-$2').toLowerCase();
  expect(s).toEqual('test-name-path');
});
```
Therefore, I think we are ok not to add a new dependency. 

Overall, I am thinking we will leave `vscode-jest` jest flags unchanged, but adding a new setting `jest.useDashedArgs` (jest's document used the term dashed args). We will pass that argument as part of the runnerWorkspace, which is constructed [here](https://github.com/jest-community/vscode-jest/blob/8037beb4ec0d3f5942b161211809f332cbd7f52c/src/JestExt/helper.ts#L94). You can follow "settings.shell" to see how we pass a setting all the way through to `jest-editor-support`.

On the `jest-editor-support` side, the `ProjectWorkspace` and the related types need to be modified to take in the new flag. And the actual argument case conversion will only need to take place in `Runner._getArgs()`, if `jest.useDashedArgs` is true, otherwise (undefined or false), do nothing, i.e. we will not do dash => camel conversion, it's a very limited single-direction conversion on the args it added or from `options.args`.

I hope it makes sense, let me know what you think.

**Comment by connectdotz** [comment]
Hi @vhdirk, are you still interested in finishing this PR?

**Comment by connectdotz** [comment]
close via #1034. Thanks to everyone who participated.

**Pull request closed without merging**
