### PR TITLE
remove release message

### LINKED ISSUE #761: Notification appears every time a new workspace is opened
### Environment

1. `vscode-jest version`: 4.1.1
2. `node -v`: 16.8.0
3. `npm -v` or `yarn --version`: yarn@1.22.11
4. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): react-scripts@3.1.1
5. your vscode-jest settings if customized:
    - `"jest.jestCommandLine": "NODE_OPTIONS=--experimental-vm-modules npx jest"` (for native ES module support)
6. Operating system: macOS 11.5.2

### Prerequisite
- are you able to run jest test from the command line? Yes
- how do you run your tests from the command line? (for example: `npm run test` or `node_modules/.bin/jest`) `yarn test`

### Steps to Reproduce

Create a workspace, such as by opening a folder, opening a workspace, or creating a new project with Jest

### Expected Behavior

No more notifications, as I already used the new test explorer with the Jest extension before

### Actual Behavior

Notification containing "vscode-jest now supports the official vscode test explorer."

### PR DESCRIPTION
**Pull request by connectdotz**
Removing the release notification since 4.1 has been released over a week so most users should be pretty familiar with the new changes. It seems hard to find the right balance of informative and not-to-be-annoying... 

fix #761

### CODE REVIEW

**Comment by connectdotz** [comment]
used this PR to test danger ci setup... tried a few ways to resolve danger CI issue, none has quite worked. Looks like there are 2 options for OSS (see [instruction](https://danger.systems/js/guides/getting_started.html#setting-up-danger-to-run-on-your-ci)), but neither is ideal... decided to just report error directly from the `dangerfile.ts` to at least output the actual error in the run-log...

**Comment by connectdotz** [comment]
@orta you are the danger-js expert, are you ok with our approach?

**Comment by connectdotz** [comment]
his PR only removed code, the decrease of coverage is purely ratio. Looks like @orta is busy, we will go with the current config until there are better ideas...

**Comment by orta** [comment]
Yeah, seems reasonable to me

**Pull request merged**
