### PR TITLE
Update README.md adding maintainers

### PR DESCRIPTION
**Pull request by orta**

### CODE REVIEW

**Comment by seanpoulter** [comment]
Should we add @vvo, @bookman25, and @connectdotz too?

**Comment by orta** [comment]
Aye, done

**Comment by orta** [comment]
Hah, sure, I can remove you 👍

**Comment by seanpoulter** [comment]
Put yourself first @orta. :1st_place_medal: Don't make me add a commit. :stuck_out_tongue_closed_eyes:

**Comment by seanpoulter** [comment]
Thanks @orta.

**Pull request merged**
