### PR TITLE
Toggle coverage overlay without changing documents

### PR DESCRIPTION
**Pull request by seanpoulter**
When toggled, the coverage overlay was not updated or removed from the visible text editors. This commit fixes this bug and updates all visible editors.

While fixing the bug I've shuffled around the files. I've renamed `Coverage.ts` as `CoverageMapProvider.ts` for clarity. Explicitly moving the responsiblity of maintaining the current coverage map lets us replace the `JestExt.coverage` property, and remove the `coverageMap` argument when calling `showCoverageOverlay(editor, coverageMap)`.

The `overlay.ts` file has been split into two files: one to manage the overlay visibility, and one to control the overlay format. For now, the `CoverageOverlay.ts` will use the `DefaultFormatter.ts`.
<br/>
cc @bookman25 -- Here's that coverage refactoring with tests.

### CODE REVIEW

**Comment by orta** [comment]
Wanna get this rebase'd and merge - then I'll ship a new release?

**Comment by seanpoulter** [comment]
Sure, I'll rebase after work @orta. 😉 🚀

**Comment by orta** [comment]
Got yourself a legit fail:

```
 FAIL  tests/JestExt.test.ts (9.465s)
  ● JestExt › updateWithData() › should update coverage map
    TypeError: Cannot read property 'coverageMap' of undefined
      
      at JestExt.updateWithData (src/JestExt.ts:324:55)
      at MockRunner.jestProcess.on.on (src/JestExt.ts:95:18)
      at emitOne (events.js:96:13)
      at MockRunner.emit (events.js:188:7)
      at Object.it (tests/JestExt.test.ts:169:25)
      at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by seanpoulter** [comment]
Ah, yes. I fixed the merge conflicts but didn't define test behavior for the new function to downcase Windows drive letters. The auto-mock returned `undefined` and broke things.

I've rebased and it works OK. The coverage code lens doesn't disappear when you toggle though. I'll open an issue for it. :disappointed:

**Comment by orta** [comment]
OK - shipped this as 2.6.0

screen shot 2018-01-29 at 4 09 29 pm

**Pull request merged**
