### PR TITLE
Add a setting for collecting coverage

### PR DESCRIPTION
**Pull request by stephtr**
[Jest/#5836](https://github.com/facebook/jest/pull/5836) enabled switching whether or not Jest should collect coverage information by a workspace attribute. This PR adds a setting to control that attribute.

Points to talk about:

- I defaulted the (boolean) setting to `null`, since supplying `false` would add the `--no-coverage` flag.
- Toggling coverage overlay may not display the overlay if `collectCoverage` isn't `true`, it therefore shows a warning message in that case. That behavior isn't perfect if `collectCoverage` has been kept at `null` and the jest command/config has been modified to nevertheless collect the information.
- The same is true for `showCoverageOnLoad`, but without a warning message.

An alternative would be that, additional to the `coverageCollect` switch, the setting could be temporarily overwritten when toggling the coverage overlay.

By the way: Sorry that I accidentally pushed these commits to the master branch, that shouldn't have happened, but I had my local branch tracking upstream instead of origin.

### CODE REVIEW

**Comment by stephtr** [comment]
One concrete use case would be if the default value of `pathToJest` would be fine for a project, one doesn't have to manually add the path to jest.
We furthermore don't force the user to use the new setting (maybe I should remove the warning message), he could still specify the `--coverage` flag within `pathToJest`.
I think it's generally cleaner to separate the path setting from the executable's extra arguments (like `pathToConfig`, which could be also supplied via).

**Comment by connectdotz** [comment]
> I think it's generally cleaner to separate the path setting from the executable's extra arguments (like pathToConfig, which can be also supplied via a setting or as a flag).

I like this idea a lot better, and I think it will probably give us more bang for the buck in the long run...  But can you give us a little bit more background on what exactly the problem we are trying to solve with this PR?

**Comment by stephtr** [comment]
There's no problem with the current status, it would be just a simplification/enhancement. But maybe it would be better to continue the discussing in #226.

**Comment by connectdotz** [comment]
oh i see, will do

**Comment by seanpoulter** [comment]
I prefer having folks configure Jest separate from configuring the UI. Jest has great documentation. If anything, I’d want to help change the config for users.

**Comment by stephtr** [comment]
In what direction would you then like #226 to go?

**Comment by seanpoulter** [comment]
I'm not sure @stephtr and while it's a good conversation to have I'd urge us to focus on our core functionality instead of the nice to have issues. While trying to fix a few regressions we've introduced in the last few weeks I seen all of these:
* test decorators not updating properly
* inline error messages that aren't being cleared
* colour escape codes appearing in messages
* the status bar message that hangs
* inline error messages in the wrong spot

I'll skim #226 and give my two cents.

**Pull request closed without merging**
