### PR TITLE
add option jest.cli.noColor for better error message display

### PR DESCRIPTION
**Pull request by Hental**
jest-editor-support Runner now support new Option `noColor` to add arg `--no-color` for jest process,so i add a new option `jest.cli.noColor (default: true)`, it can display error message better

see also: #279 

thanks :)

### CODE REVIEW

**Comment by orta** [comment]
Nice work, looks like a merge conflict though

**Comment by Hental** [comment]
thanks :),and i fork lastest repo and create a new pr

**Comment by seanpoulter** [comment]
@Hental:
> but how do i close this
<br/>

The button to close the repo is down at the bottom. I'll let you close it.

screen shot 2018-04-16 at 00 22 55

**Comment by Hental** [comment]
thanks~

**Pull request closed without merging**
