### PR TITLE
Spawn Jest command in separate shell on Windows

### LINKED ISSUE #98: Exception raised: Process failed: spawn node_modules\.bin\jest.cmd ENOENT
Enable to get this working. Using create-react-app with TypeScript. Any help appreciated

### PR DESCRIPTION
**Pull request by stephtr**
Should fix #98, adding `.cmd` won't be necessary anymore.
Updating `jest-editor-support` was necessary, `jest-snapshot` and `jest-typescript-parser` not, but I updated them anyway.

### CODE REVIEW

**Comment by stephtr** [comment]
I didn't look through the other PRs, but it's probably better to close this in favor of #215.

**Comment by orta** [comment]
Ok, so #215 is now in, shall I close this?

**Comment by seanpoulter** [comment]
I'd leave it open. It's a quick change from `src/JestExt.ts` to the change from #215. @stephtr, did you want to have a look at this again?

**Comment by stephtr** [comment]
I'll have a look at it in a few hours.

**Comment by stephtr** [comment]
Before merging this PR `index.d.ts` in `jest-editor-support` has to be updated to include the `shell` property. I will submit a PR to jest.

**Comment by seanpoulter** [comment]
Aren't we pulling types from [`typings/jest-editor-support.d.ts`](https://github.com/jest-community/vscode-jest/blob/master/typings/jest-editor-support.d.ts)?

**Comment by stephtr** [comment]
Ah thanks, I didn't notice that.

**Comment by seanpoulter** [comment]
Sweet. Thanks @stephtr.

@orta, when should we use the typings from `jest-editor-support`?

**Comment by orta** [comment]
The ideal case is to move those typings back to jest-editor-extension every so often so others can get the value from them, but it's pretty ad-hoc

**Comment by orta** [comment]
OK, I'm going to merge and ship this - it's the only PR in this release that I can't personally verify, so if this upcoming release is broken I'll need one of you two to take a look 💃

**Comment by stephtr** [comment]
[jest#5625](https://github.com/facebook/jest/pull/5625) contains the typings update for `jest-editor-support`. There are two types remaining (`TestResult` and `FormattedTestResults`), which should be moved to `typings/jest.d.ts` as they belong to the jest package (which hasn't any TypeScript definitions at all), before `jest-editor-support.d.ts` can be removed.

**Pull request merged**
