### PR TITLE
Fix #331: Support useWsl parameter

### LINKED ISSUE #331: No way to use jest installed within Windows Subsystem for Linux
### Environment

1. `node -v`: no version installed
2. `npm -v`: no version installed
3. `npm ls react-scripts` (if you haven’t ejected): N/A

4. Operating system: Windows 10 + WSL

### Steps to Reproduce

Use Windows 10 + Windows subsystem for linux. Install node/npm/jest within the subsystem only, not in windows.

### Expected Behavior

There should be a way to use the version of jest installed within WSL rather than duplicating the installation of all the tools required, once within linux and once in windows

### Actual Behavior

```
'jest' is not recognized as an internal or external command, operable program or batch file.
```
(Quite rightly, as there's absolutely no node/jest/npm installed outside WSL)

--- 

I've tried to look through docs and other open bugs but cannot find anything similar, apologies if I've missed it!
Note that I'm not sure if there are any guidelines for extension authors around using WSL, but it's e.g. possible to [debug files using node installed within WSL](https://code.visualstudio.com/updates/v1_17#_node-debugging), so assuming it's doable for extensions as well.

### PR DESCRIPTION
**Pull request by mojadev**
As discussed, now a version without any mapping in vscode-jest itself. This relies on the changes in the jest-editor-support package, so expect the CI to fail 😃

### CODE REVIEW

**Comment by connectdotz** [comment]
@seanpoulter sorry I don't have windows env... @stephtr, can you help?

**Comment by seanpoulter** [comment]
No worries. I'll see if I can get WSL setup in a VM from https://modern.ie. 😆

**Comment by mojadev** [comment]
Hey,
please don't forget that I have to update https://github.com/jest-community/jest-editor-support/ first. My PR was not merged they removed the repo (I'm doing that now)

**Comment by seanpoulter** [comment]
Hah! Thanks, I totally missed that. 😥 Need any help?
I'll review the PR for jest-editor-support and figure out how close we can get to getting a new release out.

**Comment by mojadev** [comment]
Actually, yes - I'm not sure if the new repo is really working. I needed to fix on fixture path (which pointed to ../../../../fixtures instead of ../../fixtures) but here under wsl the tests fail due to an exception in @babel/traverse (I think it's masking the actual error). Does it work for you when you check out the repo and link it to vscode-jest? I'll also try it on my Fedora system later.

**Comment by mojadev** [comment]
So, current state:
Using https://github.com/mojadev/jest-editor-support/tree/WSL_Support and https://github.com/mojadev/vscode-jest/tree/bugfix/331-wsl-configuration I can run vscode jest with wsl.
Unfortunately, the tests break and I don't know really why - my guess is that jest-editor-support updated to babel-7 and that causes incompatibilities:
See (color-convert breaks?):
https://travis-ci.org/mojadev/vscode-jest

I also get errors in jest-editor-support, in areas I didn't touch:
https://travis-ci.org/mojadev/jest-editor-support

Any ideas? @orta maybe?

**Comment by connectdotz** [comment]
@mojadev sorry took so long for us to get back to you on this issue, yes integrating with the new `jest-editor-support` turns out to be quite a drama 😱 

I think I finally got it figured out, please watch for #442, once we integrate with the new `jest-editor-support`, you can hopefully finish up this PR... sorry for the delay but help is on the way...

**Comment by mojadev** [comment]
> @mojadev sorry took so long for us to get back to you on this issue, yes integrating with the new `jest-editor-support` turns out to be quite a drama 😱
> 
> I think I finally got it figured out, please watch for #442, once we integrate with the new `jest-editor-support`, you can hopefully finish up this PR... sorry for the delay but help is on the way...

Cool! No problem - looking forward to finishing this :)

**Comment by connectdotz** [comment]
@mojadev the `jest-editor-support` has been incorporated in the `beta` branch, if you rebase this PR to `beta`, you should be able to test your change.

**Comment by stephtr** [comment]
Even Microsoft is now [deprecating the use of `useWSL`](https://code.visualstudio.com/updates/v1_36#_nodejs-debug-configuration-attribute-usewsl-is-deprecated) for Node.js debug configurations in favor of the Remote-WSL extension. I'll therefore close this PR as there is a working and supported solution to run jest within the WSL available, which additionally don't add new complexity to the `jest-editor-support` package. For further details on how to use VS Code on WSL, see [their documentation](https://code.visualstudio.com/docs/remote/wsl).

A big thank you to @mojadev for putting so much work into WSL support!

**Pull request closed without merging**
