### PR TITLE
✏️ fix Typo in command palette action

### PR DESCRIPTION
**Pull request by MrStanDu33**
This PR purpose is to fix a basic typo that occurs in the command palette.

More information on issue #758 

#trivial

### CODE REVIEW

**Review by connectdotz — APPROVED** [review]
@MrStanDu33 thanks for the PR 👍 ! 

P.S. the CI error is due to missing CHANGELOG, in case you are wondering.

**Comment by MrStanDu33** [comment]
Yeah I just figured that (the CI log is not that verbose 😆) I was just wondering if that was a  big deal, as it do not fix anything (I mean, fixing a typo is not a big fix). But if you want I can update the changelog to include my update 👌.
Let me know 💪

**Comment by connectdotz** [comment]
no problem, I updated your PR and added the "#trivial" marker so CI is happy now. I am merging it, thanks!

**Comment by MrStanDu33** [comment]
No prob' Thanks for your time ! 😄

**Pull request merged**
