### PR TITLE
Fix when "update snapshots" message is displayed

### PR DESCRIPTION
**Pull request by uucue2**
Making it so that the "update snapshots" message still shows up when multiple snapshot tests fail.

#trivial

### CODE REVIEW

**Comment by seanpoulter** [comment]
The change looks good to me. :+1:
You don't want that in the changelog @uucue2?

**Comment by seanpoulter** [comment]
This closes #209.

**Comment by HEISoftware** [comment]
@seanpoulter 

Did this not get merged into master? Just realized that the new version of the extension is still using the old condition that doesn't prompt if multiple snapshot tests fail

**Comment by uucue2** [comment]
@seanpoulter

Did this not get merged into master? Just realized that the new version of the extension is still using the old condition that doesn't prompt if multiple snapshot tests fail

**Comment by seanpoulter** [comment]
Not sure why I closed and didn't merge that, sorry!

**Comment by seanpoulter** [comment]
Sorry I can't push out a new version for you @uucue2. That's in @orta's wheelhouse.

**Comment by uucue2** [comment]
no problem - it's not blocking me by any means. it can go out whenever. thanks again!

**Comment by orta** [comment]
lolz

**Comment by seanpoulter** [comment]
For what it's worth, that's the only time I've accidentally closed one. Just checked. 😉

**Comment by orta** [comment]
Deployed as 2.6.1

**Pull request merged**
